server:
      servlet:
            context-path: /crud
      port: 8080


spring:
      profiles:
            active: druid
      devtools:
            add-properties: true
      banner:
            location: classpath:banner.txt
      data:
            mongodb:
                  uri: mongodb://192.168.0.103:27017/mytest


