server:
      servlet:
            context-path: /mongo
      port: 9001


spring:
      banner:
            location: classpath:banner.txt
      data:
            mongodb:
                  uri: mongodb://192.168.0.105:27017/mytest


